### ISSUE TITLE
Very high energy usage

### ISSUE THREAD

**Issue by yemeen** [Kyome22/GitGrass#11]
any idea why it would be this active?

![image](https://github.com/Kyome22/GitGrass/assets/11223834/8f19945c-6507-4e13-964a-6d8fabb2e79e)
![image](https://github.com/Kyome22/GitGrass/assets/11223834/74e572aa-30b5-4f8c-91dc-31bcf1f5d0d9)

**Comment by Kyome22** [comment]
@Yemeen 
Thank you for reporting the issue.
CPU usage always seems to be over 90%.
This is a pretty bad situation, so I'd like to investigate.

**Comment by Kyome22** [comment]
@Yemeen 
This issue has been fixed in version 2.4.
https://apps.apple.com/us/app/gitgrass/id1501139279?mt=12
