### ISSUE TITLE
Top right grass image error

### ISSUE THREAD

**Issue by yunjaena** [Kyome22/GitGrass#3]
# Bug Report
- version
   - macOS Catalina 10.15.3
- issue
   - top right grass image error
   - ![image](https://user-images.githubusercontent.com/41162218/77223678-23570180-6ba2-11ea-98ae-5b6ca558df29.png)

**Comment by Kyome22** [comment]
Thank you for reporting the bug.
I have already fixed this bug (App Store ver1.1).
Apparently, it was because the HTML on GitHub did not follow certain rules.
