### ISSUE TITLE
【BUG】GitHubのUI刷新に伴って草(コントリビューション)が取得できなくなっている

### ISSUE THREAD

**Issue by masebb** [Kyome22/GitGrass#4]
Swiftを書いたことないのでわかりませんが、草の色もUI刷新に伴って変更されたのが影響したのかな...?

# スクリーンショット

## 自分のコントリビューション履歴

<img width="612" alt="スクリーンショット 2020-07-02 18 24 49" src="https://user-images.githubusercontent.com/30523995/86341498-57f25300-bc91-11ea-95c1-0169ac06643c.png">

## MacOS

<img width="149" alt="スクリーンショット 2020-07-02 18 22 43" src="https://user-images.githubusercontent.com/30523995/86341356-27aab480-bc91-11ea-8159-237db9b01730.png">

## iOS

![IMG_48BAD4C5AA13-1](https://user-images.githubusercontent.com/30523995/86341389-31341c80-bc91-11ea-90d9-54b410aa462e.jpeg)

**Comment by Kyome22** [comment]
@mira-tech おっしゃる通り、GitHubのUI刷新に伴い草のパースが失敗するようになってしまっているようです。
今週末にiOS版、mac版共に修正する予定です。

**Comment by Kyome22** [comment]
@mira-tech 
iOS版、macOS版共に修正版がリリース開始されました。
ちなみに草の色が変わったことがパースに失敗する理由でした。今後草の色に些細な変更が加えられたとしても、その分も加味してパースできるようにしました。

**Comment by masebb** [comment]
早速アップデートして、動作も無事確認できました！！

ご対応ありがとうございます❤️
